### ISSUE TITLE
JacoDB misses hidden fields

### ISSUE THREAD

**Issue by sergeypospelov** [UnitTestBot/jacodb#116]
Consider this class hieararchy:
```java
public class HiddenFieldSuperClass {
    public int a, b;
}

class HiddenFieldSuccClass extends HiddenFieldSuperClass {
    public double b;
}
```
Note that though fields clashes by name, they are different. However, JacoDB misses one of the fields, so the following code fails:
```kotlin
val succClass = cp.findClass<HiddenFieldSuccClass >()
val fields = succClass.toType().fields
assertEquals(3, fields.size) // fails
```

I guess, the problem is here:

https://github.com/UnitTestBot/jacodb/blob/82c8c070ca031c47e02d435323578e461761088f/jacodb-core/src/main/kotlin/org/jacodb/impl/types/JcClassTypeImpl.kt#L284-L289

**Comment by lehvolk** [comment]
It's expected behavior. Let's examine this code:

```
class HiddenFieldSuccClass extends HiddenFieldSuperClass {
    public double b;

    void hello(){
         System.out.println(d);
         System.out.println(a);
    }
}
```

instructions of this code should reference field d from HiddenFieldSuccClass  and field a from HiddenFieldSuperClass thus type.fields will represent scope of visible fields inside class.

**Comment by lehvolk** [comment]
Problem is in that type.fields and clazz.fields return different results.
