### ISSUE TITLE
Clean up `Classes` table from unnecessary classes

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/jacodb#127]
For every run of analysis tool with JaCoDb it adds records to `Symbols` table which look identical. But only for one of such duplicate `BytecodeLocations` exists. So others could be cleaned up.

Below is partial result of following query:
```sql
select s.name, c.location_id, BL.path
from Symbols as s
         inner join Classes C
                    on s.id = C.name
     left join BytecodeLocations BL on BL.id = C.location_id
    inner join
     (select c.bytecode
      from Classes as c
      group by c.bytecode
      having count(*) > 1) bc
     on c.bytecode = bc.bytecode
order by s.name;
```

As you may note below only one path exist for unique class
![image](https://github.com/UnitTestBot/jacodb/assets/10035839/2d1e7bd5-273b-4b4a-9b3f-31621ebdda04)

**Comment by lehvolk** [comment]
Can't reproduce it in WT and in tests. Seems like database was ignited on version with bug and it was fixed.
