### ISSUE TITLE
Suport for `ldc MethodType` and `ldc Dynamic` is missing

### ISSUE THREAD

**Issue by Maccimo** [UnitTestBot/jacodb#88]
Method `RawInstListBuilder::buildLdcInsnNode()` is missing support for `ldc` with constant pool entries of type `CONSTANT_MethodType` or `CONSTANT_Dynamic` as an argument.
An attempt to load class file with above mentioned instructions will fail with "Unknown LDC constant" exception.

The following gist can be used as a reproducer: https://gist.github.com/Maccimo/b760180649ec645827a058745d95b749
It contains both compiled class and `asmtools jasm` source for class file.

**Comment by lehvolk** [comment]
Thanks for this issue. It will be fixed soon. 

By the way we accept pull requests.
